import type { Metadata } from 'next';
import { Roboto, Roboto_Mono } from 'next/font/google';
import './globals.scss';

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['400', '500', '700']
});

const robotoMono = Roboto_Mono({
	subsets: ['latin'],
	weight: ['400', '500', '700']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full w-full" data-theme="cupcake">
			<body
				className={`${roboto.className} ${robotoMono.className} box-border min-h-full w-full pb-12 text-lg antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
